# NumPy 基本使用方法示例
NumPy 是 Python 中用于科学计算的基础库，提供了高性能的多维数组对象和相关工具。

In [17]:
import numpy as np

# 创建一个一维数组
arr1 = np.array([1, 2, 3, 4, 5])
print("一维数组:", arr1)

# 创建一个二维数组
arr2 = np.array([[1, 2], [3, 4]])
print("二维数组:", arr2)

一维数组: [1 2 3 4 5]
二维数组: [[1 2]
 [3 4]]


In [18]:
# 数组的形状
print("arr1的形状:", arr1.shape)
print("arr2的形状:", arr2.shape)

# 数组的数据类型
print("arr1的数据类型:", arr1.dtype)

arr1的形状: (5,)
arr2的形状: (2, 2)
arr1的数据类型: int32


In [19]:
# 创建特定数组
zeros_arr = np.zeros((3, 4))  # 创建3x4的全0数组
ones_arr = np.ones((2, 3))    # 创建2x3的全1数组
identity_arr = np.eye(3)      # 创建3x3的单位矩阵
print("全0数组:", zeros_arr)
print("全1数组:", ones_arr)
print("单位矩阵:", identity_arr)

全0数组: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
全1数组: [[1. 1. 1.]
 [1. 1. 1.]]
单位矩阵: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# 数组的基本运算
arr = np.array([1, 2, 3, 4])
print("原数组:", arr)
print("数组加法 (arr + 10):", arr + 10)
print("数组乘法 (arr * 2):", arr * 2)
print("数组平方:", arr ** 2)

原数组: [1 2 3 4]
数组加法 (arr + 10): [11 12 13 14]
数组乘法 (arr * 2): [2 4 6 8]
数组平方: [ 1  4  9 16]


In [21]:
# 数组的索引和切片
print("arr[0]:", arr[0])
print("arr[1:3]:", arr[1:3])

# 多维数组的索引
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("二维数组:", arr_2d)
print("arr_2d[1, 2]:", arr_2d[1, 2])
print("arr_2d的第一行:", arr_2d[0])
print("arr_2d的前两行:", arr_2d[:2])
print("arr_2d的前两行和前两列:", arr_2d[:2, :2])

arr[0]: 1
arr[1:3]: [2 3]
二维数组: [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_2d[1, 2]: 6
arr_2d的第一行: [1 2 3]
arr_2d的前两行: [[1 2 3]
 [4 5 6]]
arr_2d的前两行和前两列: [[1 2]
 [4 5]]


In [22]:
# 数组的统计运算
print("数组元素的和:", np.sum(arr))
print("数组元素的平均值:", np.mean(arr))
print("数组元素的最大值:", np.max(arr))
print("数组元素的最小值:", np.min(arr))

数组元素的和: 10
数组元素的平均值: 2.5
数组元素的最大值: 4
数组元素的最小值: 1


In [23]:
# 数组的形状变换
reshaped_arr = arr.reshape((2, 2))
print("重塑后的数组:", reshaped_arr)

# 数组的拼接
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
concatenated_arr = np.concatenate([arr_a, arr_b])
print("拼接后的数组:", concatenated_arr)

重塑后的数组: [[1 2]
 [3 4]]
拼接后的数组: [1 2 3 4 5 6]


In [26]:
# 数组的广播
A = np.array([[1,2],[3,4]])
B = np.array([10, 20])
print("A:", A)
print("B:", B)
print("A * B:", A * B)

A: [[1 2]
 [3 4]]
B: [10 20]
A * B: [[10 40]
 [30 80]]


广播图例子

<img src='../assets/广播.png' width='1500'><br>